# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Test Run
email: n/a
description: > # this means to ignore newlines until "baseurl:"
  My name is Tony, and I am confused about most things about programming and web development. This is my first attemt to launch a websit through github and Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tonytudor3
github_username:  TonyPaws

# Build settings
markdown: kramdown
